export interface Project {
  id: string;
  title: string;
  shortDescription: string;
  fullDescription: string;
  techStack: string[];
  liveUrl: string;
  githubUrl?: string;
  logoUrl: string;
  category: string;
  problem: string;
  solution: string;
  impact: string;
  metrics: Array<{ label: string; value: string }>;
  architectureLayers: string[];
  screenshotUrl?: string; // Automatically generated by backend
}

export const projectsData: Project[] = [
  {
    id: 'quicklink',
    title: 'QuickLink',
    shortDescription: 'Enterprise-grade SaaS URL shortening and productivity platform.',
    fullDescription: 'QuickLink is an all-in-one web platform designed to simplify link sharing through URL shortening, QR code generation, and productivity tools. The project focuses on high performance, clean UI, security, and SEO visibility. It includes features like custom alias support, browser-based QR tools, and a Pomodoro focus tracker.',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'SEO Optimization', 'Frontend UI/UX'],
    liveUrl: 'https://qlynk.vercel.app/',
    githubUrl: 'https://github.com/deepdeyiitgn/Quicklink',
    logoUrl: '/quicklink-logo.svg',
    category: 'SaaS / Productivity',
    problem: 'Sharing long links and study resources across devices was slow and inconsistent.',
    solution: 'Built a focused URL + QR workflow with clean UI and performance-first architecture.',
    impact: 'Improved sharing speed and centralized digital productivity utilities in one node.',
    metrics: [
      { label: 'Core Features', value: '5+' },
      { label: 'Latency Focus', value: '<300ms target' },
      { label: 'UI Flow Steps', value: '2-step sharing' },
    ],
    architectureLayers: ['Frontend SPA', 'URL Processing', 'QR Utility', 'SEO Layer'],
    screenshotUrl: '/69eb00ccd24c4d75c62cc04c.png'
  },
  {
    id: 'studybot',
    title: 'StudyBot',
    shortDescription: 'Focus & Productivity Discord Bot for student communities.',
    fullDescription: 'StudyBot is a modular Discord bot built to help students stay focused and consistent. It provides study utilities, reminders, streak tracking, and interactive commands to support disciplined study habits. Features include AI-assisted study support and hybrid command systems (slash + prefix).',
    techStack: ['Node.js', 'Discord.js', 'Automation', 'Feature Planning'],
    liveUrl: 'https://studybots.vercel.app/',
    githubUrl: 'https://github.com/deepdeyiitgn/studybot',
    logoUrl: '/quicklink-logo.svg',
    category: 'Automation / Discord',
    problem: 'Student communities lacked consistent accountability and focus automation.',
    solution: 'Implemented reminder, streak, and command-driven productivity workflows for Discord.',
    impact: 'Enabled structured, gamified consistency inside student study groups.',
    metrics: [
      { label: 'Command Modes', value: 'Slash + Prefix' },
      { label: 'Primary Modules', value: '4' },
      { label: 'Community Fit', value: 'Student-first' },
    ],
    architectureLayers: ['Bot Commands', 'Task Scheduler', 'Reminder Engine', 'Community Layer'],
    screenshotUrl: '/69eb01deef048160b7374d68.png'
  },
  {
    id: 'discord-top-user-audio-engine',
    title: 'Discord Top User & Audio Engine',
    shortDescription: 'Enterprise-grade Discord bot with custom audio CDN and productivity trackers.',
    fullDescription: 'An enterprise-grade Discord bot featuring a Flask web management dashboard, custom 96kbps audio compression, HF Space CDN integration, interactive RAM-based games, and an advanced AFK/Pomodoro focus tracker.',
    techStack: ['Python', 'Discord.py', 'Flask', 'MongoDB', 'Tailwind CSS', 'Render', 'FFmpeg'],
    liveUrl: 'https://deepdey.onrender.com/',
    githubUrl: 'https://github.com/deepdeyiitgn/Discord-Top-User',
    logoUrl: '/quicklink-logo.svg',
    category: 'Discord Bot / Audio Engine',
    problem: 'Needed a scalable, rate-limit-proof bot for music streaming, activity tracking, and focus management without external API dependencies.',
    solution: 'Developed a Python-based bot with local FFmpeg audio compression, 10MB chunked uploads to an independent HF Space CDN, and MongoDB state persistence.',
    impact: 'Delivered a seamless music and productivity experience with an independent web dashboard for remote server administration.',
    metrics: [
      { label: 'Audio Compression', value: '96kbps MP3' },
      { label: 'File Handling', value: '10MB Chunked Uploads' },
      { label: 'State Management', value: 'MongoDB + RAM Buffer' },
    ],
    architectureLayers: ['Discord.py Bot Engine', 'Flask Web Dashboard', 'FFmpeg Processing', 'HF CDN Integration'],
    screenshotUrl: '/discord-activity-bot.png'
  },
  {
    id: 'transparent-clock',
    title: 'Transparent Clock',
    shortDescription: 'A highly customizable Windows desktop overlay for focus tracking.',
    fullDescription: 'A privacy-first, completely offline Windows desktop application designed for students and creators. It provides a transparent clock overlay that stays on top of other windows, bundled with productivity tools like a dedicated Pomodoro timer and deep analytics with 24-hour heatmaps.',
    techStack: ['C#', '.NET', 'Windows SDK', 'JSON Storage', 'Inno Setup'],
    liveUrl: 'https://qlynk-clock.vercel.app/',
    githubUrl: 'https://github.com/deepdeyiitgn/Clock-Overlays',
    logoUrl: 'https://clock.qlynk.me/assets/images/logo.png',
    category: 'Windows Utility',
    problem: 'Students needed a non-distracting, always-visible focus utility with local privacy.',
    solution: 'Created an offline-first Windows overlay with clock, pomodoro, and analytics.',
    impact: 'Delivered a focused environment with transparent UI and local-first data control.',
    metrics: [
      { label: 'Data Policy', value: 'Local-first' },
      { label: 'Platform', value: 'Windows native' },
      { label: 'Core Utilities', value: '3+' },
    ],
    architectureLayers: ['WPF UI', 'Session Tracking', 'Local Storage', 'Utility Integrations'],
    screenshotUrl: '/69eb01798f30a15224010404.png' 
  },
  {
    id: 'birthday-surprise-app',
    title: 'Birthday Surprise App | Interactive Ecosystem',
    shortDescription: 'A magical, multi-profile interactive web application featuring personalized gamified journeys and hardware integrations.',
    fullDescription: 'A highly interactive React frontend designed to deliver bespoke digital birthday experiences. It features a smart URL-based authentication system that routes different users to entirely unique visual themes, custom-animated timelines, and manifestation games. It also leverages advanced browser APIs, including an isolated multi-track audio controller for seamless crossfading and MediaStream Microphone API integration allowing users to physically "blow out" a digital candle.',
    techStack: ['React 19', 'TypeScript', 'Tailwind CSS', 'Vite 6', 'HTML5 Audio API', 'MediaStream API'],
    liveUrl: 'https://m.qlynk.me/?pass=demo@123',
    githubUrl: 'https://m.qlynk.me/?pass=demo@123',
    logoUrl: 'https://m.qlynk.me/favicon.jpeg',
    category: 'Interactive Web App / Gamification',
    problem: 'Needed a scalable, engaging way to celebrate multiple birthdays with deeply personalized, zero-crossover digital experiences served from a single application architecture.',
    solution: 'Engineered a multi-profile React application utilizing URL-based secure routing, dynamic state isolation, physics-based gamification, and custom hardware access for immersive interactions.',
    impact: 'Created a highly engaging bespoke digital gifting platform that handles 8 entirely distinct user journeys, showcasing advanced frontend state management, CSS keyframe animations, and complex media handling.',
    metrics: [
      { label: 'Profiles', value: '8 Unique Experiences' },
      { label: 'Hardware UI', value: 'Mic-Detected Candle' },
      { label: 'Audio System', value: 'Isolated Track Crossfading' },
    ],
    architectureLayers: ['React 19 View Layer', 'URL Authentication Logic', 'MediaStream Input', 'Custom Audio Controller Class'],
    screenshotUrl: '/m-qlynk-me-1024x768desktop-192b9e.png'
  },
  {
    id: 'qlynk-node-server',
    title: 'QLYNK Node Server',
    shortDescription: 'Highly secure private cloud storage and streaming datacenter.',
    fullDescription: 'Engineered to run entirely on Hugging Face Spaces (Free Tier), it acts as a self-sustaining media vault with an integrated Telegram ingestion bot, dynamic anti-hacker defenses (Tarpit/Honeypot), and a cinematic web player with cryptographic token vault security.',
    techStack: ['Python', 'FastAPI', 'Docker', 'Hugging Face Spaces', 'Cryptographic Security'],
    liveUrl: 'https://deydeep-deqlynk.hf.space/',
    githubUrl: 'https://github.com/deepdeyiitgn/static-files',
    logoUrl: '/quicklink-logo.svg',
    category: 'Cloud Storage / CDN',
    problem: 'Required a resilient media-serving backend with security controls on constrained infra.',
    solution: 'Built a FastAPI-based media vault with ingestion pipeline and tokenized access.',
    impact: 'Established a private serving architecture with secure access patterns and automation.',
    metrics: [
      { label: 'Runtime', value: 'HuggingFace Spaces' },
      { label: 'Security Layer', value: 'Token + defense' },
      { label: 'Core Scope', value: 'Media vault + streaming' },
    ],
    architectureLayers: ['API Gateway', 'Storage Layer', 'Ingestion Bot', 'Security Policies'],
    screenshotUrl: '/69eb02bff3d3b01f6326a557.jpg' 
  },
  {
    id: 'personal-portfolio',
    title: 'Deep Dey | Digital Ecosystem',
    shortDescription: 'Advanced personal portfolio with a custom CMS and Live Status tracking.',
    fullDescription: 'A highly optimized, full-stack personal portfolio acting as my central digital identity. It goes beyond a static site by featuring a highly secure, custom-built admin dashboard, MongoDB-backed journal publishing, and a real-time glowing "Live Status" widget that updates visitors on my current activities.',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Vercel Serverless APIs', 'MongoDB'],
    liveUrl: 'https://deepdey.vercel.app/',
    githubUrl: 'https://github.com/deepdeyiitgn/My-Portfolio',
    logoUrl: '/assets/images/myphoto.png',
    category: 'Web Platform / CMS',
    problem: 'Needed a centralized, zero-dependency platform to showcase projects, write journals, and broadcast live status with complete data ownership.',
    solution: 'Engineered a React-based frontend with a protected Vercel serverless backend and MongoDB for dynamic, cost-effective content management.',
    impact: 'Established an independent digital hub with absolute control over UI/UX, database storage, and real-time visitor engagement.',
    metrics: [
      { label: 'Architecture', value: 'Full-stack Custom CMS' },
      { label: 'Database', value: 'MongoDB Storage' },
      { label: 'Unique Feature', value: 'Live Status Ecosystem' },
    ],
    architectureLayers: ['React Frontend', 'Vercel Serverless API', 'MongoDB Data Layer', 'Admin Dashboard'],
    screenshotUrl: '/69eb02bff3d3b01626326a557.jpg'
  },
];
